### ISSUE TITLE
Read position from Wild Dinos

### ISSUE THREAD

**Issue by kkm** [timhuijgen/ark-files#1]

**Comment by timhuijgen** [comment]
I can have a look if I can add it, I'm not sure though if this information is actually in these files.

**Comment by timhuijgen** [comment]
@kkm I had a quick look, but I couldn't find any reference to the dino's or their location in either the arkprofile or arktribe files. Don't think it's stored in there.

**Comment by kkm** [comment]
Are you sure? App larkator can read this position
![](https://capturei.tikatoy.com/r/AyRpiINPHXCx.png)

sorry for late reply....you know ark needs time..

**Comment by timhuijgen** [comment]
Currently this package only reads the player/tribe save files, and not the world save files. I don't know if I have time to look at adding the other ones aswel.
